import type { Trip } from '../types';

export const seedTrips: Trip[] = [
  {
    id: 'TR001',
    source: 'Gandhinagar Depot',
    destination: 'Ahmedabad Hub',
    vehicleId: 'v1',
    driverId: 'd1',
    cargoWeight: 350,
    plannedDistance: 57,
    status: 'Dispatched',
    eta: '45 min',
    createdAt: '2026-07-05',
  },
  {
    id: 'TR002',
    source: 'Ahmedabad Hub',
    destination: 'Surat Depot',
    vehicleId: 'v2',
    driverId: 'd2',
    cargoWeight: 4200,
    plannedDistance: 265,
    actualDistance: 270,
    fuelConsumed: 110,
    status: 'Completed',
    eta: '—',
    createdAt: '2026-07-04',
  },
  {
    id: 'TR003',
    source: 'Vadodara Hub',
    destination: 'Rajkot Terminal',
    vehicleId: 'v5',
    driverId: 'd3',
    cargoWeight: 600,
    plannedDistance: 210,
    status: 'Dispatched',
    eta: '1h 10m',
    createdAt: '2026-07-06',
  },
  {
    id: 'TR004',
    source: 'Vatva Industrial Area',
    destination: 'Sanand Warehouse',
    vehicleId: 'v6',
    driverId: 'd4',
    cargoWeight: 2800,
    plannedDistance: 45,
    status: 'Draft',
    eta: 'Awaiting driver',
    createdAt: '2026-07-06',
  },
  {
    id: 'TR006',
    source: 'Mansa',
    destination: 'Kalol Depot',
    vehicleId: null,
    driverId: null,
    cargoWeight: 0,
    plannedDistance: 30,
    status: 'Cancelled',
    eta: 'Vehicle sent to shop',
    createdAt: '2026-07-03',
  },
];
